apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:a0baf7d8d99fe4525b8fd0fceaea332f388e2fec
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
