apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:94b7a56550e81d98e9e4e8db7292d2fd7a15a577
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
