apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:11e899cbf1809aca19a329fe2f0b8b80d90e02ce
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
