apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:ee261fb5a626eee24ab64d158ce8aa609425cc5a
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
