apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:cf371497652fe08c9ee98b316a88fbd617ebea91
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
