apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:f258547ddd85fc18040ba90b563af02a8f78d6cc
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
