apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:19a4610e4308633bfe3f5b3397831c57d4178896
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
