apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:9d834067aab717096d4e9edca4a9644180bc863a
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
