apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:610bec5b65c825109404fec3251cfb4a0c553932
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
