apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:86ff459763637ebb07b38a5dc94d4e4533e06e8e
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
