apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:008b4e7c1dd300b60d76f91e8b09662a69d01cd3
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
