apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:fed9a0d56685b8ac11bf9be99563eb63cfdc320b
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
