apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:d1c04c8ae492a593f273138927d1af724cbfe5fe
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
