apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:c75c2d7cd5b4c9a911bf3466886ccba773926621
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
