apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:3314acb3aacbe4f6fa68a68087cf77bb8eee6bf1
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
