apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:d1df5a8a14a44132c8d6d35a12e028bf58dd85f4
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
