apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:45c65c150d33e2807cbd6f1b0f557baa82600cab
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
