apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:5e92862ad0c7e9dbe40344b6e28b3f456c1743f6
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
