apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:3c8e5a1a7cbe718192ede722705990e337cae9f4
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
