apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:e50676d003b7a1f7132571d5ef6dd157463d715e
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
