apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:6735530d5904bed008d93e8bbc5add4dc93c37f7
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
