apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:d55d60ab4ef1830beada2f2d05fbea8acd8a3bff
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
