apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:838440af58411f7583e3474fa7f72b8a648f7199
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
