apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:39554b2c67fe4412665f4d2256ea824151c85ac8
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
