apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:25671e88ed030463bf80cd0a9a15e94f81795db9
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
