apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:66140c22c19c96dcfbede63b2f0ba636226ecf46
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
