apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:c7ddda844de8b978a80463ce665cd1c3204c679c
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
