apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:aa7413f0b010a721accaf8ad12de87ad27693dc5
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
