apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:d390e7d321a16f23073c2b35f6a4eee066a16d5e
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
