apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:5cc25563c619639e97965f48d21503f7d5ad078e
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
