apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:040f4cef12b34ae407454bc2b66580995e24beb9
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
