apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:5cfb522c29d5c14dcfdb1057d94f9b9d11874ec5
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
