apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:00aa8a3308365a88499c52fc3218f124ffb7ef5d
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
