apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:850f0f58c14cf9b78a4e011788aa7cbf4235a7fa
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
