apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:dc9df1c043eddcc9b8c4e3f33512691c51011db7
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
