apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:48f1bcde55bf495634c1fba6d093207f08fe4e5c
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
