apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:d194d7e32f59a9d2a648762788a914558c9ace36
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
