apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:2b5701ad048538f9831050b915688b65bbf746a5
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
