apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:a0b8840126bbc8fd7c8b5687d2d685d63d1df5b1
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
