apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:438fc4270576abe13853ae76d76b7d1e753009d4
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
