apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:c57f833a53cf8943512c1368b5d2e6730faf9eae
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
