apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:ac91c58f8823226d933dcd8cf56d3669ca4dc595
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
