apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:32e31cb66a3c1c9dea812a67d614a44ab3d32085
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
