apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:7d3c862a9309cb0347fc69db3009725900b3dcf1
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
