apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:ebfcebdf42599f6a80ac5222b3dbd086984a51bf
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
