apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:f71c7029624c6ff1df9a2e5fde5aa472cca53707
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
