apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:b56aeb3bf47c8a7509a52d181ce7d0214c5fb6a8
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
