apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:8874b1a818a1c24ae6840b947a1a8b504470aba2
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
