apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:0f3a03ecb30fae539934a722f0efcaec7001a155
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
