apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:cb44827d23151d22f5ee32c6c3ea6355a9edf85d
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
