apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:3c4a99249265e53106dfe498586427b7a1074939
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
