apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:76f2a6b2823307722c1256e103586f6260f614d8
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
