apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:b0cd8d2ea3cb5a13749130ed832e9d047e0ef04c
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
