apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:057003fe6d8890075a80e17016c0f22adfa822de
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
