apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:4965173fe0f322d55fe4af9395eb3b5f414cf63b
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
