apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:2237807b51888137fbd528c2fcd4749a11c2c80e
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
