apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:75082bd1178c856e4898d25427f033bd16d9f9d4
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
