apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:9e3364bfa332e28f74c6b29da8baf27b4118ebd9
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
