apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:8e2a31fe813324e898e0d2485e4329ef2bd5b389
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
