apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:c585571f0048c72be47f65fc24a1554a628e6dcb
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
