apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:a2ec811d32ca54caf08a0f8f2ec803059fc39526
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
