apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:f0d16df3cad2820d5bb99e03a65c3fd2b50eec66
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
