apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:08cb667b81470cfded4ab25c8e6ba0d05987b7f4
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
