apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-container
        image: 10449/simple-html:f5dbe0a26ba679e94e09a3523f7664480ee18549
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: dockerhub-secret
